import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Baskervville,
  IBM_Plex_Sans,
} from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/components/ui/floating-navbar";
import { Footer } from "@/components/ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const baskervville = Baskervville({
  variable: "--font-baskervville",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  {
    name: "Home",
    link: "/",
  },
  {
    name: "For Buyers",
    link: "/for-buyers",
  },
  {
    name: "For Sellers",
    link: "/for-sellers",
  },
  {
    name: "For Investors",
    link: "/for-investors",
  },
  {
    name: "About Us",
    link: "/about-us",
    menuItems: [
      {
        name: "Our Mission",
        link: "/about-us/our-mission",
      },
      {
        name: "Contact Us",
        link: "/about-us/contact-us",
      },
      {
        name: "Our Blog",
        link: "/about-us/our-blog",
      },
    ],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${baskervville.variable} ${ibmPlexSans.variable} font-[var(--font-baskervville)] antialiased`}
      >
        <FloatingNav navItems={navItems} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
